config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  # devise_for :users
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  # devise_scope :user do
  #   # Redirests signing out users back to sign-in
  #   get 'users', to: 'devise/sessions#new'
  # end

  resources :channels do
    post :join
    resources :messages, only: %i[new create]
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/channel.rb
# frozen_string_literal: true

class Channel < ApplicationRecord
  has_many :channel_users
  has_many :users, through: :channel_users
  has_many :messages, through: :channel_users

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/channels_controller.rb
# frozen_string_literal: true

class ChannelsController < ApplicationController
  before_action :set_channel, only: %i[show]

  def index
    @channels = Channel.all.order(name: :asc)
  end

  def new
    @channel = Channel.new
  end

  def create
    @channel = Channel.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  def join
    @channel = Channel.find_by(id: params[:channel_id])

    if @channel.channel_users.find_or_create_by(user: current_user)
      redirect_to channel_path(@channel), notice: t('channels.notices.joined')
    else
      redirect_to channel_path, alert: t('channels.alerts.empty')
    end
  end

  def show
    @new_message = Message.new
  end

  private

  def channel_params
    params.require(:channel).permit(:name)
  end

  def set_channel
    @channel = current_user.channels.find_by(id: params[:channel_id].presence || params[:id])
  end
end

app/helpers/channels_helper.rb
# frozen_string_literal: true

module ChannelsHelper
end

app/views/channels/index.html.erb
<h2>Channels </h2>

<% if @channels.present? %>
  <% @channels.each do |channel| %>
    <% if channel.users.include? current_user %>
      <h3>Go to channel: <%= link_to channel.name, channel_path(channel), class: "btn" %></h3>
    <% else %>
      <h3><%= button_to 'Join', channel_join_path(channel), method: :post, data: { confirm: "Are you sure?" }, class: "btn btn--success" %></h3>
    <% end %>
  <% end %>
<% else %>
  <h3>No channels found. Please create a new channel</h3>
<% end %>

app/views/channels/show.html.erb
<% if current_user && current_user.channels.present? %>
	<span><%= button_to 'Back', root_path, method: :get, class: "btn btn-primary"%> </span>

  <h1>#<%= @channel.name%></h1>

  <section class="messages">
    <%= turbo_stream_from "channel_#{@channel.id}" %>
    <%= turbo_frame_tag "messages" do %>
      <%= render @channel.messages %>
    <% end %>
  </section>

  <%= turbo_frame_tag "new_message" do %>
    <%= render "messages/form", message: @new_message, channel: @channel %>
  <% end %>
<% end %>