config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  # devise_for :users
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  # devise_scope :user do
  #   # Redirests signing out users back to sign-in
  #   get 'users', to: 'devise/sessions#new'
  # end

  resources :channels do
    post :join
    resources :messages, only: %i[new create]
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :channel_user
  validates :content, presence: true

  after_create :broadcast_message
  default_scope { order(created_at: :asc) }

  def broadcast_message
    broadcast_append_to(
      "channel_#{channel_user.channel_id}",
      target: 'messages',
      partial: 'messages/message',
      locals: { message: self }
    )
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  before_action :set_channel_and_user

  def new; end

  def create
    @message = @channel_user.messages.new(message_params)

    @new_message = if @message.save
                     Message.new
    else
                      @message
    end

    render :new, formats: :turbo_stream
  end

  private

  def set_channel_and_user
    @channel_user ||= current_user.channel_users.find_by(channel_id: params[:channel_id])
    @channel ||= @channel_user.channel
  end

  def message_params
    params.require(:message).permit(:content)
  end
end

app/views/messages/_form.html.erb
<%= form_for message, url: channel_messages_path(channel), method: :post, html: { class: "new-message" } do |f| %>
  <div class="field">
    <%= f.text_area :content %>
  </div>
  <%= f.submit 'Send', class: "btn btn-primary"%>
<% end %>

app/views/messages/_message.html.erb
<%= turbo_stream.append "messages" do %>
  <article class="message">
    <div class="small">
      <i>
      <span><%= message.channel_user.user.name %></span>
      <span><%= message.created_at.strftime("%d %b %Y, %I:%M %p") %></span>
      </i>
    </div>
    <div class="">
      <%= message.content %>
    </div>
    <hr/>
  </article>
<% end %>

app/views/messages/new.turbo_stream.erb
<%= turbo_stream.replace "new_message" do %>
  <%= render "form", message: @new_message, channel: @channel %>
<% end %>